wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.8
    start_time: 1672869537.487914
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.8
      5: 0.13.7
      8:
      - 1
      - 3
      - 5
batch_size:
  desc: null
  value: 128
depth:
  desc: null
  value: 3
dropout:
  desc: null
  value: 0.1
epochs:
  desc: null
  value: 300
first_filter_size:
  desc: null
  value: 8
kernel_size:
  desc: null
  value: 5
kld_weight:
  desc: null
  value: 1
latent_dim:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: rmsprop
rec_loss:
  desc: null
  value: L2
reduction:
  desc: null
  value: sum
