wandb_version: 1

batch_size:
  value: 128
depth:
  value: 4
dropout:
  value: 0.4
epochs:
  value: 300
first_filter_size:
  value: 5
kernel_size:
  value: 3
kld_weight:
  value: 0.1
latent_dim:
  value: 6
learning_rate:
  value: 0.01
optimizer:
  value: sgd
rec_loss:
  value: L2
reduction:
  value: sum
