wandb_version: 1

batch_size:
  value: 128
depth:
  value: 3
dropout:
  value: 0.1
epochs:
  value: 300
first_filter_size:
  value: 8
kernel_size:
  value: 5
kld_weight:
  value: 1
latent_dim:
  value: 4
learning_rate:
  value: 0.001
optimizer:
  value: rmsprop
rec_loss:
  value: L2
reduction:
  value: sum
