wandb_version: 1

batch_size:
  value: 128
depth:
  value: 3
dropout:
  value: 0.4
epochs:
  value: 300
first_filter_size:
  value: 7
kernel_size:
  value: 3
kld_weight:
  value: 10
latent_dim:
  value: 8
learning_rate:
  value: 0.001
optimizer:
  value: nadam
rec_loss:
  value: L2
reduction:
  value: sum
